version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: odoo         
      POSTGRES_PASSWORD: odoo      
      POSTGRES_DB: "${APELLIDO}${XX}"  
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo              
      - DB_PASSWORD=odoo          
      - DB_NAME=${APELLIDO}${XX}   
    ports:
      - "8089:8069"
    depends_on:
      - db

volumes:
  odoo-db-data:
